In [11]:
# all scrapped data combiner for all states csv to data frame states in it w

import pandas as pd
import numpy as np

In [12]:
#csv to dataframe
df_buses_1AP = pd.read_csv(r"D:\Scraped_data\dfDATA_AP.csv")
df_buses_2CTU = pd.read_csv(r"D:\Scraped_data\dfDATA_CTU.csv")
df_buses_3HP = pd.read_csv(r"D:\Scraped_data\dfDATA_HP.csv")
df_buses_4KE = pd.read_csv(r"D:\Scraped_data\dfDATA_KE.csv")
df_buses_5PJ = pd.read_csv(r"D:\Scraped_data\dfDATA_PJ.csv")
df_buses_6RS = pd.read_csv(r"D:\Scraped_data\dfDATA_RS.csv")
df_buses_7TG = pd.read_csv(r"D:\Scraped_data\dfDATA_TG.csv")
df_buses_8UP = pd.read_csv(r"D:\Scraped_data\dfDATA_UP.csv")
df_buses_9WB1 = pd.read_csv(r"D:\Scraped_data\dfDATA_WB1SBSTC.csv")
df_buses_10WB2 = pd.read_csv(r"D:\Scraped_data\dfDATA_WB2WBTC.csv")
df_buses_11WB3 = pd.read_csv(r"D:\Scraped_data\dfDATA_WB3NBSTC.csv")
df_buses_12WB4 = pd.read_csv(r"D:\Scraped_data\dfDATA_WB4WBSTC.csv")
df_buses_13GOA = pd.read_csv(r"D:\Scraped_data\dfDATA_GOA.csv")
df_buses_14BIHAR = pd.read_csv(r"D:\Scraped_data\dfDATA_BIHAR.csv")
df_buses_15ASSAM1 = pd.read_csv(r"D:\Scraped_data\dfDATA_ASSAM.csv")
df_buses_16ASSAM2 = pd.read_csv(r"D:\Scraped_data\dfDATA_ASSAMkaac.csv")
df_buses_17JK = pd.read_csv(r"D:\Scraped_data\dfDATA_jkf.csv")

Final_df=pd.concat([df_buses_1AP,df_buses_2CTU,df_buses_3HP,df_buses_4KE,df_buses_5PJ,df_buses_6RS,
                    df_buses_7TG,df_buses_8UP,df_buses_9WB1,df_buses_10WB2,df_buses_11WB3,df_buses_12WB4,df_buses_13GOA,
                    df_buses_14BIHAR,df_buses_15ASSAM1,df_buses_16ASSAM2,df_buses_17JK])

Final_df

,Bus Routes Name,Bus Routes Link,Bus Name,Bus Type (Sleeper/Seater/AC/Non-AC),Departing Time,Duration,Reaching Time,Star Rating,Price,Seat Availability
0,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,APSRTC - 35085,DOLPHIN CRUISE (VOLVO / SCANIA A.C Multi Axle),18:30,06h 00m,00:30,3.9\n69,INR 720,39 Seats available
1,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,APSRTC - 3613,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",19:00,07h 42m,02:42,3.3\n24,INR 469,30 Seats available
2,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,APSRTC - 9316,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",20:20,07h 50m,04:10,4.2\n61,INR 469,26 Seats available
3,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,APSRTC - 35189,DOLPHIN CRUISE (VOLVO / SCANIA A.C Multi Axle),20:30,04h 35m,01:05,3.9\n37,INR 670,38 Seats available
4,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,APSRTC - 4046,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",21:00,06h 40m,03:40,4.2\n52,INR 469,28 Seats available
...,...,...,...,...,...,...,...,...,...,...
39,Motihari to Lucknow,https://www.redbus.in/bus-tickets/motihari-to-...,Shree Balajee Travels And Cargo,A/C Seater / Sleeper (2+1),15:00,10h 00m,01:00,1.2,1169,47 Seats available
40,Motihari to Lucknow,https://www.redbus.in/bus-tickets/motihari-to-...,Shree Balajee Travels And Cargo,A/C Sleeper (2+1),21:31,06h 30m,04:01,1.2,1349,36 Seats available
0,Tezpur to Guwahati,https://www.redbus.in/bus-tickets/tezpur-to-gu...,Assam State Transport Corporation (ASTC) - 157959,Bharat Benz A/C Seater (2+2),14:00,04h 30m,18:30,4.2\n197,INR 298,5 Seats available
1,Tezpur to Guwahati,https://www.redbus.in/bus-tickets/tezpur-to-gu...,Assam State Transport Corporation (ASTC) - 154930,Volvo AC Seater 2+2,15:45,04h 15m,20:00,3.7\n50,INR 298,22 Seats available
2,Tezpur to Guwahati,https://www.redbus.in/bus-tickets/tezpur-to-gu...,Himalayan Travels,NON A/C Seater (2+2),23:40,04h 20m,04:00,1.8\n16,INR 500,33 Seats available

In [13]:
Final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9232 entries, 0 to 2
Data columns (total 10 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Bus Routes Name                      9232 non-null   object
 1   Bus Routes Link                      9232 non-null   object
 2   Bus Name                             9232 non-null   object
 3   Bus Type (Sleeper/Seater/AC/Non-AC)  9232 non-null   object
 4   Departing Time                       9232 non-null   object
 5   Duration                             9232 non-null   object
 6   Reaching Time                        9232 non-null   object
 7   Star Rating                          9232 non-null   object
 8   Price                                9232 non-null   object
 9   Seat Availability                    9232 non-null   object
dtypes: object(10)
memory usage: 793.4+ KB

In [14]:
#convert prices to numeric
Final_df["Price"]=Final_df["Price"].str.replace("INR","")
Final_df["Price"]=Final_df["Price"].astype(float)
Final_df["Price"].fillna(480)

0      720.0
1      469.0
2      469.0
3      670.0
4      469.0
       ...
39    1169.0
40    1349.0
0      298.0
1      298.0
2      500.0
Name: Price, Length: 9232, dtype: float64

In [15]:
Final_df

,Bus Routes Name,Bus Routes Link,Bus Name,Bus Type (Sleeper/Seater/AC/Non-AC),Departing Time,Duration,Reaching Time,Star Rating,Price,Seat Availability
0,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,APSRTC - 35085,DOLPHIN CRUISE (VOLVO / SCANIA A.C Multi Axle),18:30,06h 00m,00:30,3.9\n69,720.0,39 Seats available
1,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,APSRTC - 3613,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",19:00,07h 42m,02:42,3.3\n24,469.0,30 Seats available
2,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,APSRTC - 9316,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",20:20,07h 50m,04:10,4.2\n61,469.0,26 Seats available
3,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,APSRTC - 35189,DOLPHIN CRUISE (VOLVO / SCANIA A.C Multi Axle),20:30,04h 35m,01:05,3.9\n37,670.0,38 Seats available
4,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,APSRTC - 4046,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",21:00,06h 40m,03:40,4.2\n52,469.0,28 Seats available
...,...,...,...,...,...,...,...,...,...,...
39,Motihari to Lucknow,https://www.redbus.in/bus-tickets/motihari-to-...,Shree Balajee Travels And Cargo,A/C Seater / Sleeper (2+1),15:00,10h 00m,01:00,1.2,1169.0,47 Seats available
40,Motihari to Lucknow,https://www.redbus.in/bus-tickets/motihari-to-...,Shree Balajee Travels And Cargo,A/C Sleeper (2+1),21:31,06h 30m,04:01,1.2,1349.0,36 Seats available
0,Tezpur to Guwahati,https://www.redbus.in/bus-tickets/tezpur-to-gu...,Assam State Transport Corporation (ASTC) - 157959,Bharat Benz A/C Seater (2+2),14:00,04h 30m,18:30,4.2\n197,298.0,5 Seats available
1,Tezpur to Guwahati,https://www.redbus.in/bus-tickets/tezpur-to-gu...,Assam State Transport Corporation (ASTC) - 154930,Volvo AC Seater 2+2,15:45,04h 15m,20:00,3.7\n50,298.0,22 Seats available
2,Tezpur to Guwahati,https://www.redbus.in/bus-tickets/tezpur-to-gu...,Himalayan Travels,NON A/C Seater (2+2),23:40,04h 20m,04:00,1.8\n16,500.0,33 Seats available

In [16]:
print(Final_df.columns)

Index(['Bus Routes Name', 'Bus Routes Link', 'Bus Name',
       'Bus Type (Sleeper/Seater/AC/Non-AC)', 'Departing Time', 'Duration',
       'Reaching Time', 'Star Rating', 'Price', 'Seat Availability'],
      dtype='object')

In [17]:
# Convert "New" to "4.0" as a string
Final_df["Star Rating"] = Final_df["Star Rating"].str.replace("New", "4.0")

# Strip any leading/trailing spaces
Final_df["Star Rating"] = Final_df["Star Rating"].str.strip()

# Split and take the first part
Final_df["Star Rating"] = Final_df["Star Rating"].str.split().str[0]

# Convert to numeric, coercing errors to NaN
Final_df["Star Rating"] = pd.to_numeric(Final_df["Star Rating"], errors='coerce')

# Fill NaN values with 3.0
Final_df["Star Rating"].fillna(3.0, inplace=True)

C:\Users\Shers\AppData\Local\Temp\ipykernel_20728\1287431212.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Final_df["Star Rating"].fillna(3.0, inplace=True)

In [18]:
Final_df

,Bus Routes Name,Bus Routes Link,Bus Name,Bus Type (Sleeper/Seater/AC/Non-AC),Departing Time,Duration,Reaching Time,Star Rating,Price,Seat Availability
0,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,APSRTC - 35085,DOLPHIN CRUISE (VOLVO / SCANIA A.C Multi Axle),18:30,06h 00m,00:30,3.9,720.0,39 Seats available
1,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,APSRTC - 3613,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",19:00,07h 42m,02:42,3.3,469.0,30 Seats available
2,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,APSRTC - 9316,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",20:20,07h 50m,04:10,4.2,469.0,26 Seats available
3,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,APSRTC - 35189,DOLPHIN CRUISE (VOLVO / SCANIA A.C Multi Axle),20:30,04h 35m,01:05,3.9,670.0,38 Seats available
4,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,APSRTC - 4046,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",21:00,06h 40m,03:40,4.2,469.0,28 Seats available
...,...,...,...,...,...,...,...,...,...,...
39,Motihari to Lucknow,https://www.redbus.in/bus-tickets/motihari-to-...,Shree Balajee Travels And Cargo,A/C Seater / Sleeper (2+1),15:00,10h 00m,01:00,1.2,1169.0,47 Seats available
40,Motihari to Lucknow,https://www.redbus.in/bus-tickets/motihari-to-...,Shree Balajee Travels And Cargo,A/C Sleeper (2+1),21:31,06h 30m,04:01,1.2,1349.0,36 Seats available
0,Tezpur to Guwahati,https://www.redbus.in/bus-tickets/tezpur-to-gu...,Assam State Transport Corporation (ASTC) - 157959,Bharat Benz A/C Seater (2+2),14:00,04h 30m,18:30,4.2,298.0,5 Seats available
1,Tezpur to Guwahati,https://www.redbus.in/bus-tickets/tezpur-to-gu...,Assam State Transport Corporation (ASTC) - 154930,Volvo AC Seater 2+2,15:45,04h 15m,20:00,3.7,298.0,22 Seats available
2,Tezpur to Guwahati,https://www.redbus.in/bus-tickets/tezpur-to-gu...,Himalayan Travels,NON A/C Seater (2+2),23:40,04h 20m,04:00,1.8,500.0,33 Seats available

In [19]:
# info after the data type change
Final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9232 entries, 0 to 2
Data columns (total 10 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Bus Routes Name                      9232 non-null   object
 1   Bus Routes Link                      9232 non-null   object
 2   Bus Name                             9232 non-null   object
 3   Bus Type (Sleeper/Seater/AC/Non-AC)  9232 non-null   object
 4   Departing Time                       9232 non-null   object
 5   Duration                             9232 non-null   object
 6   Reaching Time                        9232 non-null   object
 7   Star Rating                          9232 non-null   float64
 8   Price                                9232 non-null   float64
 9   Seat Availability                    9232 non-null   object
dtypes: float64(2), object(8)
memory usage: 793.4+ KB

In [10]:
#only if you want to exclude buse with price more than 7000
Final_df = Final_df[Final_df["Price"] <= 7000]

In [20]:
Final_df

,Bus Routes Name,Bus Routes Link,Bus Name,Bus Type (Sleeper/Seater/AC/Non-AC),Departing Time,Duration,Reaching Time,Star Rating,Price,Seat Availability
0,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,APSRTC - 35085,DOLPHIN CRUISE (VOLVO / SCANIA A.C Multi Axle),18:30,06h 00m,00:30,3.9,720.0,39 Seats available
1,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,APSRTC - 3613,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",19:00,07h 42m,02:42,3.3,469.0,30 Seats available
2,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,APSRTC - 9316,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",20:20,07h 50m,04:10,4.2,469.0,26 Seats available
3,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,APSRTC - 35189,DOLPHIN CRUISE (VOLVO / SCANIA A.C Multi Axle),20:30,04h 35m,01:05,3.9,670.0,38 Seats available
4,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,APSRTC - 4046,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",21:00,06h 40m,03:40,4.2,469.0,28 Seats available
...,...,...,...,...,...,...,...,...,...,...
39,Motihari to Lucknow,https://www.redbus.in/bus-tickets/motihari-to-...,Shree Balajee Travels And Cargo,A/C Seater / Sleeper (2+1),15:00,10h 00m,01:00,1.2,1169.0,47 Seats available
40,Motihari to Lucknow,https://www.redbus.in/bus-tickets/motihari-to-...,Shree Balajee Travels And Cargo,A/C Sleeper (2+1),21:31,06h 30m,04:01,1.2,1349.0,36 Seats available
0,Tezpur to Guwahati,https://www.redbus.in/bus-tickets/tezpur-to-gu...,Assam State Transport Corporation (ASTC) - 157959,Bharat Benz A/C Seater (2+2),14:00,04h 30m,18:30,4.2,298.0,5 Seats available
1,Tezpur to Guwahati,https://www.redbus.in/bus-tickets/tezpur-to-gu...,Assam State Transport Corporation (ASTC) - 154930,Volvo AC Seater 2+2,15:45,04h 15m,20:00,3.7,298.0,22 Seats available
2,Tezpur to Guwahati,https://www.redbus.in/bus-tickets/tezpur-to-gu...,Himalayan Travels,NON A/C Seater (2+2),23:40,04h 20m,04:00,1.8,500.0,33 Seats available

In [21]:
# replacing the nan value
Final_df = Final_df.replace({np.nan: None})

In [22]:
Final_df

,Bus Routes Name,Bus Routes Link,Bus Name,Bus Type (Sleeper/Seater/AC/Non-AC),Departing Time,Duration,Reaching Time,Star Rating,Price,Seat Availability
0,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,APSRTC - 35085,DOLPHIN CRUISE (VOLVO / SCANIA A.C Multi Axle),18:30,06h 00m,00:30,3.9,720.0,39 Seats available
1,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,APSRTC - 3613,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",19:00,07h 42m,02:42,3.3,469.0,30 Seats available
2,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,APSRTC - 9316,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",20:20,07h 50m,04:10,4.2,469.0,26 Seats available
3,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,APSRTC - 35189,DOLPHIN CRUISE (VOLVO / SCANIA A.C Multi Axle),20:30,04h 35m,01:05,3.9,670.0,38 Seats available
4,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,APSRTC - 4046,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",21:00,06h 40m,03:40,4.2,469.0,28 Seats available
...,...,...,...,...,...,...,...,...,...,...
39,Motihari to Lucknow,https://www.redbus.in/bus-tickets/motihari-to-...,Shree Balajee Travels And Cargo,A/C Seater / Sleeper (2+1),15:00,10h 00m,01:00,1.2,1169.0,47 Seats available
40,Motihari to Lucknow,https://www.redbus.in/bus-tickets/motihari-to-...,Shree Balajee Travels And Cargo,A/C Sleeper (2+1),21:31,06h 30m,04:01,1.2,1349.0,36 Seats available
0,Tezpur to Guwahati,https://www.redbus.in/bus-tickets/tezpur-to-gu...,Assam State Transport Corporation (ASTC) - 157959,Bharat Benz A/C Seater (2+2),14:00,04h 30m,18:30,4.2,298.0,5 Seats available
1,Tezpur to Guwahati,https://www.redbus.in/bus-tickets/tezpur-to-gu...,Assam State Transport Corporation (ASTC) - 154930,Volvo AC Seater 2+2,15:45,04h 15m,20:00,3.7,298.0,22 Seats available
2,Tezpur to Guwahati,https://www.redbus.in/bus-tickets/tezpur-to-gu...,Himalayan Travels,NON A/C Seater (2+2),23:40,04h 20m,04:00,1.8,500.0,33 Seats available

In [ ]:
#convert the combined dataframe to csv with all state bus details    
path=r"D:\Scraped_data\dfFinal_all.csv"
Final_df.to_csv(path,index=False)

In [ ]:
# then manually open the csv file and replace data in seat availability by changing ex 39 seats availability to 39 and 1 seat available to 1 
#then edit duration part manually similar to other values for some cells as they have like 0-3h 0-15m instead of 03h 15m 
#then change the names of the coloumns similar to the table column names as in the file MYSQL.ipynb then run that file MYSQL.ipynb